steemit/steem-python

steem/account.py

Found this just now,  newer versions of funcy lack the simple_funcs namespace

minor bugfix

---

docs/examples.rst

Issue #47
Added block to  get_last_line to check if the target file is empty and return EOF if empty.
fp.read() will return EOF if a file is empty. 
The problem was with the seek. If there were no lines in the file, the seek function would fail with Invalid Index.

Example syncing blockchain to flat file: return EOF if file empty

---

steem/steem.py
steembase/http_client.py

A call for something like `steem.get_accounts(["ned"])` currently calls a [getattr trampoline](https://github.com/steemit/steem-python/blob/33dc65cc6fc85c51f57e182abe5fadff573cfa6e/steem/steem.py#L54-L61) which causes the method to be delegated to a [method](https://github.com/steemit/steem-python/blob/33dc65cc6fc85c51f57e182abe5fadff573cfa6e/steem/steemd.py#L469-L474) on the `Steemd` class which is really just a wrapper around the `exec` [method](https://github.com/steemit/steem-python/blob/33dc65cc6fc85c51f57e182abe5fadff573cfa6e/steembase/http_client.py#L135) of the HTTP client class, ultimately generating a JSONRPC HTTP request that looks like this:
```
{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_account", ["ned"]]}
```
In general these wrappers may …

Implement generic API access

---

steembase/base58.py

The testnet address prefix is defined in `steemd` [here](https://github.com/steemit/steem/blob/aee19938c9d121466496e56251619de4ecdf5455/libraries/protocol/include/steem/protocol/config.hpp#L18) as `"TST"`.  The `steem-python` code must be updated to match, or it will spew warnings when using this code to process testnet pubkeys.

Use correct testnet address prefix

---

steembase/http_client.py

The elif-statement in its original form would never be executed, so the exception would never be raised. This could potentially lead to an infinite loop.

Update for loop to infinity in http_client.py

---

steem/converter.py

I found I was getting incorrect results based on this method, so I dug into the code in steemit/steem, and discovered the math was being done improperly. 
https://github.com/steemit/steem/blob/8cd5f688d75092298bcffaa48a543ed9b01447a6/libraries/chain/steem_evaluator.cpp#L1169-L1190
I believe this pull request contains what the math should be to derive proper rshares for a given amount of SP.

Corrected sp_to_rshares math

---

steem/post.py

Voting using `.vote()` checks if the post is archived, and if it is, it raises the `VotingInvalidOnArchivedPost` error.
However, prior to this fix, it checked if the `net_rshares` of the post was 0, which would also fire if the post did not have any votes on it yet. This fix allows posts that aren't archived but have 0 votes to be voted on.

Fix Error Causing Voting to Fail

---

steembase/base58.py

This eliminates the following warning:
Format GLS unkown. You've been warned!

base58.py: add GLS to known_prefixes

---

steem/wallet.py

This enables support for multiple steem-like networks.

wallet.py: obtain key prefix from chain_params

---

steem/transactionbuilder.py

This fixes transaction signing with non-steem networks. In steem we're
always have STM prefix for pubkeys, but in other networks prefix is
different, so transactionbuilder just cannon find the proper
privkey-pubkey pair whether prefixes does not match.

transactionbuilder.py: set operations.default_prefix explicitly

---

steem/utils.py
steembase/storage.py

This closes #176 . However, this uncovers another bug, #181 .

Fixed storage.py to properly reference compat_bytes

---

steem/cli.py
steem/commit.py
steem/post.py
steem/steemd.py
steem/utils.py
tests/steem/test_utils.py

`construct_identifier` was responsible for formatting the permlink, and had wonky handling of the '@' at the beginning of the permlink. Removed to improve clarity.

Removed '@' from construct_identifier.

---

steem/blockchain.py

Config variable `STEEMIT_BLOCK_INTERVAL` is changed to `STEEM_BLOCK_INTERVAL`
This pull request fixes issue #163

change config var: STEEMIT_BLOCK_INTERVAL -> STEEM_BLOCK_INTERVAL

---

steem/commit.py
steem/transactionbuilder.py
steem/utils.py
steembase/types.py

`types.JsonObj` would occasionally generate unicode data due to the functionality of `json.loads`. The `compat_json` method was pulled from [this stackoverflow question](https://stackoverflow.com/questions/956867/how-to-get-string-objects-instead-of-unicode-from-json/13105359#13105359). This is a crucial fix for Python 2.7 support.

Python 2.7 compat layer for Types.JsonObj

---

steembase/http_client.py
tests/steem/test_broadcast.py
tests/steem/test_steemd.py

Resolve #164
- Assume provided nodes are running appbase and use condenser_api.
- Check for a specific error that a non-appbase node would return
- If present, save the endpoint to a 'downgraded` registry, and retry
This PR changes exception flow -- it is more thorough and retries are more reliable.

assume appbase, downgrade on error

---

steem/__init__.py
steembase/http_client.py
tests/steem/test_transactions.py

This will allow for node cycling when a node is down or fat-fingered when initially set.

Added JSONDecodeError to list of retriable errors

---

steem/cli.py
steem/utils.py
steem/wallet.py
steembase/storage.py

Closes #222 .
`MasterPassword`, as used in `wallet.py` and `storage.py` is in fact a randomly generated key encryption key stored in SQLiteConfig. It has been refactored to `KeyEncryptionKey`.
`password` within the `MasterPassword` class was in fact a user supplied pass phrase for unlocking the KEK, so was refactored to userPassphrase.
I didn't muck around much in `cli.py` as I know we are intending to rewrite that with click.

Refactored MasterPassword

---

steem/cli.py
steembase/bip38.py
tests/steembase/test_bip38.py
tests/steembase/test_bip38_pylibscrypt.py
tests/steembase/test_bip38_scrypt.py

Closes #181 
`scrypt.hash` requires that the password and salt are `str` in Python 2.7. This PR adds a code path to bip38.py that typecasts the values to strings.
All tests are passing, however I'm not certain this will entirely fix the issue, if there are passwords that have illegal characters in them, this will fail.

Added branch in bip38 for Python 2.7 compatibility.

---

steembase/operations.py
tests/steem/test_transactions.py

Closes #226 
- Adds change_recovery_account operation to steembase.

Change Recovery Account Serialization and Signing

---

steem/converter.py

get_dynamic_global_properties() no longer returns reward_fund info. Use get_reward_fund() instead.

fix sbd_to_rshares

---

steem/post.py

curation_reward_pct() from 30 minutes to 15 minutes

HF20 changed curation reward penalty

---

steembase/bip38.py

Local PR for @AlexChien #245:
> when run command
> ```
> steempy addkey
> ```
> and input proper wif key and have wallet unlocked, it throws 
> 
> ```
> new() missing 1 required positional argument: 'mode'
> ```
> 
> fixed by recommendation found at https://steemit.com/steemdev/@anthonyadavisii/steem-python-bip38-wallet-error-with-fix

Community - fix missing positional argument: mode
